%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Solving symbolically for the transformation matrix of one joint given 
% D-H parameters alpha_i, a_i, theta_i, and d_i
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
syms alpha_i a_i theta_i d_i;

R_x = [1, 0, 0, 0; ...
       0, cos(alpha_i), -sin(alpha_i), 0; ...
       0, sin(alpha_i), cos(alpha_i), 0; ...
       0, 0, 0, 1];
D_x = [1, 0, 0, a_i; ...
       0, 1, 0, 0; ...
       0, 0, 1, 0; ...
       0, 0, 0, 1];
R_z = [cos(theta_i), -sin(theta_i), 0, 0; ...
       sin(theta_i), cos(theta_i), 0, 0; ...
       0, 0, 1, 0; ...
       0, 0, 0, 1];
D_z = [1, 0, 0, 0; ...
       0, 1, 0, 0; ...
       0, 0, 1, d_i; ...
       0, 0, 0, 1];
   
T = R_x*D_x*R_z*D_z;